<?php
/** @var \App\Model\User $user */   //говорим, что переменная $user - это объект класса ModelUser
$user = $this->user;    //переданная в шаблон модель доступна как $this->user
?>

<?php if ($user): ?>
    name: <?= $user->getName(); ?> <br>
    gender: <?= $user->getGenderString(); ?> <br>
    registered: <?= $user->getCreatedAt(); ?> <br>
<?php else: ?>
Пользователь не найден
<?php endif; ?>

<?php echo "свойства: <br>";
var_dump(get_object_vars($this));
//get_class_vars($this);
//get_class_methods($this);

    var_dump($this->Anton);