<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>Форма авторизации</title>
    <!--    <link rel="stylesheet" href="style.css">-->
    <style>
        .form-signup {
            width: 500px;
            height: 400px;
            background: antiquewhite;
            margin: 0 auto;
            display: flex;
            flex-direction: column;
            padding: 50px 50px;
        }
        .form-styling {
            margin-bottom: 30px;
        }
    </style>
</head>
<body>
<div class="container">

    <form class="form-signup" action="" method="post" name="authorizationForm">

        <label for="email">Email</label>
        <input class="form-styling" type="text" name="email" placeholder=""/>
        <label for="password">Password</label>
        <input class="form-styling" type="text" name="password" placeholder=""/>

        <input class="submit" type="submit" value="Войти" />
    </form>
    <div>
        <h2>Ещё не зарегистрировался? Тогда <a href="/user/register">ЖМИ</a></h2>
    </div>
</div>
<?= $this->var;
?>

</body>
</html>